/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medical.store.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import medical.store.management.system.D.ConnectionProvider;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author Vipul
 */
public class AddStock extends javax.swing.JFrame {
  public int checkmedicineId = 0;
    private String medicineId;
  
    /**
     * Creates new form UpdateStock
     */
    public AddStock() {
        initComponents();
        this.setTitle("Add Stock");
        this.setSize(1030,610);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtmedid = new javax.swing.JTextField();
        txtmedname = new javax.swing.JTextField();
        txtdom = new javax.swing.JTextField();
        txtdoe = new javax.swing.JTextField();
        txtpur = new javax.swing.JTextField();
        txtsuppname = new javax.swing.JTextField();
        txtquan = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setText("Add Stock");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 200, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Medicine ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 129, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Medicine Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 213, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Supplier Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 283, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Date of Manufacture");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 129, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Date of Expiry");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 213, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Purchase Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 283, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Price Per Unit");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 100, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 100, 40));

        txtmedid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmedidActionPerformed(evt);
            }
        });
        txtmedid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmedidKeyReleased(evt);
            }
        });
        getContentPane().add(txtmedid, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 157, 300, 30));

        txtmedname.setMaximumSize(new java.awt.Dimension(1000, 700));
        txtmedname.setMinimumSize(new java.awt.Dimension(500, 350));
        txtmedname.setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(txtmedname, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 247, 300, 30));

        txtdom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdomActionPerformed(evt);
            }
        });
        getContentPane().add(txtdom, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 157, 300, 30));
        getContentPane().add(txtdoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 247, 300, 30));

        txtpur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpurActionPerformed(evt);
            }
        });
        getContentPane().add(txtpur, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 317, 300, 30));
        getContentPane().add(txtsuppname, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 317, 300, 30));

        txtquan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquanActionPerformed(evt);
            }
        });
        getContentPane().add(txtquan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 300, 30));

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 300, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vipul\\Downloads\\medical-healthcare-blue-color\\26807.jpg")); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, -1720, -1, -1));

        setSize(new java.awt.Dimension(998, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtdomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdomActionPerformed

    private void txtquanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquanActionPerformed

    private void txtpurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpurActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         StockPurchased stockpurchased=new StockPurchased();
        stockpurchased.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String medicineId = txtmedid.getText();
    String medicineName = txtmedname.getText();
    String supplierName = txtsuppname.getText();
    String quantity = txtquan.getText();
    String dom = txtdom.getText();
    String doe = txtdoe.getText();
    String purchasedate = txtpur.getText();
    String priceperunit = txtprice.getText();
    int qty = Integer.parseInt(quantity);
     double prc = Double.parseDouble(priceperunit);
     double Price=2*prc;
     double total = qty*Price;
     String Total = Double.toString(total);
     String priceper = Double.toString(Price);
     
     SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    if(medicineId.equals("")){
        JOptionPane.showMessageDialog(null, "Medicine Id field is required."); 
    }else if(medicineName.equals("")){
        JOptionPane.showMessageDialog(null, "Medicine Name field is required.");
    }else if(supplierName.equals("")){
        JOptionPane.showMessageDialog(null, "Supplier Name field is required.");
    }else if(quantity.equals("")){
        JOptionPane.showMessageDialog(null, "Quantity field is required.");
    }else if(dom.equals("")){
        JOptionPane.showMessageDialog(null, "Date of Manufacture field is required.");
    }else if(doe.equals("")){
        JOptionPane.showMessageDialog(null, "Date of Expiry field is required.");
    }else if(purchasedate.equals("")){
        JOptionPane.showMessageDialog(null, "Purchase Date field is required.");
    }else if(priceperunit.equals("")){   
        JOptionPane.showMessageDialog(null, "Price Per Unit field is required.");
    }else {
        try{
             dateFormat.setLenient(false); 
            Date parsedDom = dateFormat.parse(dom);
            String formattedDom = dateFormat.format(parsedDom);
            Date parsedDoe = dateFormat.parse(doe);
            String formattedDoe = dateFormat.format(parsedDoe);
            Date parsedPurchasedate = dateFormat.parse(purchasedate);
            String formattedPurchaseDate = dateFormat.format(parsedPurchasedate);
            
             ConnectionProvider connectionProvider = new ConnectionProvider();
            Connection con = connectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("insert into stock(Id,medicineName,supplierName,dom,doe,purchasedate,quantity,price) values(?,?,?,?,?,?,?,?)", Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, medicineId);
            ps.setString(2, medicineName);
            ps.setString(3, supplierName);
            ps.setString(4, dom);
            ps.setString(5, doe);
            ps.setString(6, purchasedate);
            ps.setString(7, quantity);
            ps.setString(8, priceperunit);
            ps.executeUpdate();

            ResultSet generatedKeys = ps.getGeneratedKeys();
            if (generatedKeys.next()) {
                int stockId = generatedKeys.getInt(1);

                PreparedStatement st = con.prepareStatement("insert into inventory(stock_id,Id,medicineName,dom,doe,quantity,price,totalPrice) values(?,?,?,?,?,?,?,?)");
                st.setInt(1, stockId);
                st.setString(2, medicineId);
                st.setString(3, medicineName);
                st.setString(4, dom);
                st.setString(5, doe);
                st.setString(6, quantity);
                st.setString(7, priceper);
                st.setString(8, Total);
                st.executeUpdate();
            }

            JOptionPane.showMessageDialog(null, "Stock Added Successfully.");
            setVisible(false);
            new AddStock().setVisible(true);
        } 
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Date Field is invalid. Use the format 'dd/MM/yyyy'.");
       }           
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtmedidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmedidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmedidActionPerformed

    private void txtmedidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmedidKeyReleased
     
    }//GEN-LAST:event_txtmedidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtdoe;
    private javax.swing.JTextField txtdom;
    private javax.swing.JTextField txtmedid;
    private javax.swing.JTextField txtmedname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtpur;
    private javax.swing.JTextField txtquan;
    private javax.swing.JTextField txtsuppname;
    // End of variables declaration//GEN-END:variables
}
