/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medical.store.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import medical.store.management.system.D.ConnectionProvider;

/**
 *
 * @author PRINCE
 */
public class AddSupp extends javax.swing.JFrame {
public String MobileNumberPattern = "^[0-9]*$";
public int checkSupplier_ID = 0;
    /**
     * Creates new form AddSupp
     */
    public AddSupp() {
        initComponents();
        this.setTitle("Add Supplier");
        this.setSize(1030,610);
         txtLabel.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtsuppid = new javax.swing.JTextField();
        txtsuppname = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vipul\\Downloads\\floppy-disk.png")); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vipul\\Downloads\\left-arrow (1).png")); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 120, 40));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 32)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vipul\\Downloads\\agreement (1).png")); // NOI18N
        jLabel1.setText("ADD  SUPPLIER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Supplier_ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 129, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 233, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Supplier Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        txtsuppid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtsuppid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsuppidActionPerformed(evt);
            }
        });
        txtsuppid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsuppidKeyReleased(evt);
            }
        });
        getContentPane().add(txtsuppid, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 166, 300, 30));

        txtsuppname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtsuppname, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 300, 30));

        txtmobile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 276, 300, 30));

        txtaddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 300, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Mobile Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        txtLabel.setText("jLabel8");
        txtLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLabelKeyReleased(evt);
            }
        });
        getContentPane().add(txtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 203, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vipul\\Downloads\\medical-healthcare-blue-color\\26807.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1090, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Supplier supplier=new Supplier();
        supplier.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    String Id = txtsuppid.getText();
    String supplierName = txtsuppname.getText();
    String mobileNumber = txtmobile.getText();
    String address = txtaddress.getText();
   
    if(Id.equals("")){
        JOptionPane.showMessageDialog(null, "Supplier ID field is required.");
    }else if(checkSupplier_ID == 1){
       JOptionPane.showMessageDialog(null, "This supplier ID already exist."); 
     }else if(supplierName.equals("")){
        JOptionPane.showMessageDialog(null, "Supplier Name field is required.");
    }else if(mobileNumber.equals("")){
        JOptionPane.showMessageDialog(null, "Mobile number field is required.");
     }else if(!mobileNumber.matches(MobileNumberPattern) || mobileNumber.length()!=10){
        JOptionPane.showMessageDialog(null, "Mobile Number field is invalid.");
    }else if(address.equals("")){
        JOptionPane.showMessageDialog(null, "Address field is required.");
    }else {
        try{
             ConnectionProvider connectionProvider = new ConnectionProvider();
            Connection con = connectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("insert into supplier(Id,supplierName,mobileNumber,address) values(?,?,?,?)");
            ps.setString(1, Id);
            ps.setString(2, supplierName);
            ps.setString(3, mobileNumber);
            ps.setString(4, address);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Supplier Added Successfully.");
            setVisible(false);
            new AddSupp().setVisible(true);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
       }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtLabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLabelKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtLabelKeyReleased

    private void txtsuppidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsuppidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsuppidActionPerformed

    private void txtsuppidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsuppidKeyReleased
        // TODO add your handling code here:
         String Id = txtsuppid.getText();
    if (!Id.equals("")) {
        txtLabel.setVisible(true);
        txtLabel.setText("");
        checkSupplier_ID = 0;
        
        try {
            ConnectionProvider connectionProvider = new ConnectionProvider();
            Connection con = connectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from supplier where Id = '" + Id + "'");
            while (rs.next()) {
                checkSupplier_ID = 1; 
            }
           
            if (checkSupplier_ID == 1) {
                txtLabel.setText("This supplier ID already exists");
            } else {
                txtLabel.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    } else {
        txtLabel.setVisible(false);
    }
    }//GEN-LAST:event_txtsuppidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSupp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel txtLabel;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtsuppid;
    private javax.swing.JTextField txtsuppname;
    // End of variables declaration//GEN-END:variables
}
