/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medical.store.management.system;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import medical.store.management.system.D.ConnectionProvider;
import medical.store.management.system.D.Path;
import medical.store.management.system.O.OpenPdf;



/**
 *
 * @author PRINCE
 */
public class Cart extends javax.swing.JFrame {
     public String MobileNumberPattern = "^[0-9]*$";
     private int finalTotalPrice = 0;
     private String username ="";
     private String bill_id = "";

    /**
     * Creates new form Cart
     */
    public Cart() {
        initComponents();
    }
     public Cart(String tempUsername) {
        initComponents();
        username = tempUsername;
        setLocationRelativeTo(null);
    }
  
    private void clearMedicineField(){
        txtmedname.setText("");
        txtquantity.setText("");
        txtprice.setText("");
        txttotal.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        medtable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmedname = new javax.swing.JTextField();
        txtquantity = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        txtcart = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        carttable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lblftp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setText("CART");

        jLabel2.setText("Search");

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        medtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine ID", "Medicine Name", "Date of Expiry", "Quantity"
            }
        ));
        medtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medtableMouseClicked(evt);
            }
        });
        medtable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                medtableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(medtable);

        jLabel3.setText("Medicine Name");

        jLabel4.setText("Price Per Unit");

        jLabel5.setText("Quantity");

        jLabel6.setText("Total Price");

        txtmedname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmednameActionPerformed(evt);
            }
        });

        txtquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtquantityKeyReleased(evt);
            }
        });

        txtcart.setText("Add To Cart");
        txtcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcartActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        carttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Quantity", "Price Per Unit", "Total Price"
            }
        ));
        carttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carttableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(carttable);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Grand Total Price");

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Generate Bill");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblftp.setText("00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(121, 121, 121)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(357, 357, 357)
                                .addComponent(jLabel1)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtmedname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lblftp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(txtcart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmedname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcart)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jLabel7)
                            .addComponent(lblftp)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void txtmednameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmednameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmednameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EmpDashboard ed = new EmpDashboard();
        ed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
         DefaultTableModel obj=(DefaultTableModel) medtable.getModel();
     TableRowSorter<DefaultTableModel> obj1=new TableRowSorter<>(obj);
     medtable.setRowSorter(obj1);
     obj1.setRowFilter(RowFilter.regexFilter(search.getText()));
    }//GEN-LAST:event_searchKeyReleased

    private void medtableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_medtableComponentShown
        // TODO add your handling code here:
      
    }//GEN-LAST:event_medtableComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) medtable.getModel();
        try{
            ConnectionProvider connectionProvider = new ConnectionProvider();
            Connection con = connectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from inventory");
            while(rs.next()) {
                model.addRow(new Object[]{rs.getString("Id"),rs.getString("medicineName"),rs.getString("doe"),rs.getString("quantity")});
            }
        txtmedname.setEditable(false);
        txtprice.setEditable(false);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void medtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medtableMouseClicked
        // TODO add your handling code here:
     int index = medtable.getSelectedRow();
    TableModel model = medtable.getModel();
    String medicineName = model.getValueAt(index, 1).toString(); 

    try {
        ConnectionProvider connectionProvider = new ConnectionProvider();
        Connection con = connectionProvider.getCon();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("select * from inventory where medicineName = '" + medicineName + "'");
        
        if (rs.next()) {
            txtmedname.setText(rs.getString("medicineName"));
            txtquantity.setText(""); 
            txtprice.setText(rs.getString("price"));
            txttotal.setText(""); 
        }
    }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
   
    }//GEN-LAST:event_medtableMouseClicked

    private void txtquantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquantityKeyReleased
        // TODO add your handling code here:
        String quantity = txtquantity.getText();
        if(!quantity.equals("")){
            String price = txtprice.getText();
            int totalprice = Integer.parseInt(quantity) * Integer.parseInt(price);
            txttotal.setText(String.valueOf(totalprice));
        }
        else{
            txttotal.setText("");
        }
    }//GEN-LAST:event_txtquantityKeyReleased

    private void txtcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcartActionPerformed
        // TODO add your handling code here:
     
    String quantity = txtquantity.getText();
    String medicineName = txtmedname.getText();

    if (!quantity.isEmpty() && !medicineName.isEmpty()) {
        String price = txtprice.getText();
        String total = txttotal.getText();
        int checkStock = 0;
        int checkMedicineExists = 0;

        try {
            ConnectionProvider connectionProvider = new ConnectionProvider();
            Connection con = connectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from inventory where medicineName = '" + medicineName + "'");
            while (rs.next()) {
                if (rs.getInt("quantity") >= Integer.parseInt(quantity)) {
                    checkStock = 1;
                } else {
                    JOptionPane.showMessageDialog(null, "Medicine is out of Stock.");
                    return;  // Exit the method if out of stock.
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            return;  // Exit the method on exception.
        }

        DefaultTableModel dtm = (DefaultTableModel) carttable.getModel();

        if (carttable.getRowCount() != 0) {
            for (int i = 0; i < carttable.getRowCount(); i++) {
                if (dtm.getValueAt(i, 0).equals(medicineName)) {
                    checkMedicineExists = 1;
                    JOptionPane.showMessageDialog(null, "Medicine already exists in the cart.");
                }
            }
        }

        if (checkMedicineExists == 0) {
            dtm.addRow(new Object[]{medicineName, quantity, price, total});
            finalTotalPrice += Integer.parseInt(total);
            lblftp.setText(String.valueOf(finalTotalPrice));
        }

        clearMedicineField();
    } else {
        JOptionPane.showMessageDialog(null, "Quantity and Medicine name fields are required.");
    }
    }//GEN-LAST:event_txtcartActionPerformed

    private void carttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carttableMouseClicked
        // TODO add your handling code here:
        int index = carttable.getSelectedRow();
        int a =  JOptionPane.showConfirmDialog(null, "Do you want to remove this medicine","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            TableModel model = carttable.getModel();
            String total = model.getValueAt(index, 3).toString();
            finalTotalPrice = finalTotalPrice - Integer.parseInt(total);
            lblftp.setText(String.valueOf(finalTotalPrice));
            ((DefaultTableModel) carttable.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_carttableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
         if (finalTotalPrice != 0) {
      SimpleDateFormat timestampFormat = new SimpleDateFormat("yyyyMMddHHmmss");
            String bill_id = "Bill-" + timestampFormat.format(new Date());
            DefaultTableModel dtm = (DefaultTableModel) carttable.getModel();
            if(carttable.getRowCount()!=0){
                for (int i = 0; i < carttable.getRowCount(); i++){
                    try {
                        ConnectionProvider connectionProvider = new ConnectionProvider();
                        Connection con = connectionProvider.getCon();
                        Statement st = con.createStatement();
                        st.executeUpdate("update inventory set quantity=quantity-" +Integer.parseInt(dtm.getValueAt(i,1).toString()) + " where price="+Integer.parseInt(dtm.getValueAt(i, 2).toString()));
                       } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                       }

                }
            }    
        try{
         SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
          Calendar cal = Calendar.getInstance();
          ConnectionProvider connectionProvider = new ConnectionProvider();
          Connection con = connectionProvider.getCon(); 
          PreparedStatement ps = con.prepareStatement("insert into bill(bill_id,billdate, totalamount) values (?,?, ?)", Statement.RETURN_GENERATED_KEYS);
             ps.setString(1, bill_id);
            ps.setString(2, dateFormat.format(cal.getTime()));
            ps.setDouble(3, finalTotalPrice);
          ps.executeUpdate();
          
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
         PdfWriter.getInstance(doc, new FileOutputStream(Path.billPath+""+bill_id+".pdf"));
             doc.open();
             Paragraph pharmacyName = new Paragraph("                                              Medical Store Management System\n");
             doc.add(pharmacyName);
             Paragraph starLine = new Paragraph("**********************************************************************************************************");
             doc.add(starLine);
             Paragraph details = new Paragraph("\tBill ID: " + bill_id + "\nDate: " + new Date());
             doc.add(details);
             doc.add(starLine);
             PdfPTable tbl = new PdfPTable(4);
             tbl.addCell("Medicine Name");
             tbl.addCell("Quantity");
             tbl.addCell("Price Per Unit");
             tbl.addCell("Total Price");
             for(int i=0; i< carttable.getRowCount();i++){
                 String a = carttable.getValueAt(i, 0).toString();
                 String b = carttable.getValueAt(i, 1).toString();
                 String c = carttable.getValueAt(i, 2).toString();
                 String d = carttable.getValueAt(i, 3).toString();
                 tbl.addCell(a);
                 tbl.addCell(b);
                 tbl.addCell(c);
                 tbl.addCell(d);
             }
             doc.add(tbl);
             doc.add(starLine);
             Paragraph amt = new Paragraph("\tTotal Amount : " + (finalTotalPrice - (finalTotalPrice * 0.12)) + "\n Total GST (12%) : " + (finalTotalPrice * 0.12) + "\nGrand Total Amount : " + finalTotalPrice);
             doc.add(amt);
             doc.add(starLine);
             Paragraph thankmsg = new Paragraph (" Thank You, Please Visit Again.");
             doc.add(thankmsg);
             OpenPdf.openById(bill_id);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
             doc.close();
             setVisible(false);
             new Cart(username).setVisible(true);
    }else{
             JOptionPane.showMessageDialog(null, "Please add some medicines to cart.");
         }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable carttable;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblftp;
    private javax.swing.JTable medtable;
    private javax.swing.JTextField search;
    private javax.swing.JButton txtcart;
    private javax.swing.JTextField txtmedname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

    private String generateBillId(String bill) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String getUniqueId(String bill) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
