/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medical.store.management.system;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import medical.store.management.system.D.ConnectionProvider;
import java.sql.PreparedStatement;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author Vipul
 */
public class UpdateStock extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStock
     */
    public UpdateStock() {
        initComponents();
        this.setSize(1030,610);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        medid = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtdom = new javax.swing.JTextField();
        txtdoe = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        txtsupl = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setText("Update Stock");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Medicine ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Medicine Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 148, 161, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Supplier Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 247, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 320, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Date of Manufacture");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 148, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Date of Expiry");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 247, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Purchase Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 336, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Price Per Unit");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 421, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vipul\\Downloads\\floppy-disk.png")); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vipul\\Downloads\\left-arrow (1).png")); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, -1, -1));
        getContentPane().add(medid, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 110, 210, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 188, 204, 30));

        txtdom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdomActionPerformed(evt);
            }
        });
        getContentPane().add(txtdom, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 188, 203, 30));

        txtdoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdoeActionPerformed(evt);
            }
        });
        getContentPane().add(txtdoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 281, 203, 32));

        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 370, 203, 31));

        txtsupl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsuplActionPerformed(evt);
            }
        });
        getContentPane().add(txtsupl, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 283, 204, 31));

        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });
        getContentPane().add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 362, 203, 31));

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 455, 203, 31));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, 23));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vipul\\Downloads\\medical-healthcare-blue-color\\26807.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4600, -190, 9240, 4220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtdomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdomActionPerformed

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        StockPurchased stockpurchased=new StockPurchased();
        stockpurchased.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            int checkUserExist =0;
     String id = medid.getText();
     if(id.equals("")){
         JOptionPane.showMessageDialog(null, "Medicine ID field is required.");
     }else {
         try{
             
             ConnectionProvider connectionProvider = new ConnectionProvider();
            Connection con = connectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from stock where Id = '" + id + "'");
            while (rs.next()){
                medid.setEditable(false);
                checkUserExist = 1;
                txtName.setText(rs.getString("medicineName"));
                txtsupl.setText(rs.getString("supplierName"));
                txtdom.setText(rs.getString("dom"));
                txtdoe.setText(rs.getString("doe"));
                txtdate.setText(rs.getString("purchasedate"));
                txtprice.setText(rs.getString("price"));
                txtqty.setText(rs.getString("quantity"));
             
            }
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null, e);  
         }
         if(checkUserExist == 0){
               JOptionPane.showMessageDialog(null,"Medicine ID does not exist.");
         }
     }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
   
    String id = medid.getText();
    String name = txtName.getText();
    String sname = txtsupl.getText();
    String dom = txtdom.getText();
    String doe = txtdoe.getText();
    String price = txtprice.getText();
    String date = txtdate.getText();
    String qty = txtqty.getText();
     SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
       int qnty = Integer.parseInt(qty);
     double prc = Double.parseDouble(price);
     double Price=2*prc;
     double total = qnty*Price;
     String Total = Double.toString(total);
     String priceper = Double.toString(Price);
    try {
         dateFormat.setLenient(false);
        Date parsedDom = dateFormat.parse(dom);
        String formattedDom = dateFormat.format(parsedDom);
        Date parsedDoe = dateFormat.parse(doe);
        String formattedDoe = dateFormat.format(parsedDoe);
        
        ConnectionProvider connectionProvider = new ConnectionProvider();
        Connection con = connectionProvider.getCon();

        PreparedStatement updateStock = con.prepareStatement("UPDATE stock SET medicineName=?, supplierName=?, dom=?, doe=?, price=?, purchasedate=?, quantity=? WHERE Id=?");
        updateStock.setString(1, name);
        updateStock.setString(2, sname);
        updateStock.setString(3, dom);
        updateStock.setString(4, doe);
        updateStock.setString(5, price);
        updateStock.setString(6, date);
        updateStock.setString(7, qty);
        updateStock.setString(8, id);

        int stockUpdateCount = updateStock.executeUpdate();

        if (stockUpdateCount > 0) {
       
            PreparedStatement updateInventory = con.prepareStatement("UPDATE inventory SET medicineName=?, dom=?, doe=?, quantity=?, price=?, totalPrice=? WHERE Id=?");
            updateInventory.setString(1, name);
            updateInventory.setString(2, dom);
            updateInventory.setString(3, doe);
            updateInventory.setString(4, qty);
            updateInventory.setString(5, priceper);
            updateInventory.setDouble(6, total);
            updateInventory.setString(7, id);

            int inventoryUpdateCount = updateInventory.executeUpdate();

            if (inventoryUpdateCount > 0) {
                JOptionPane.showMessageDialog(null, "Stock and Inventory updated successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Stock updated, but Inventory update failed.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No rows updated. Stock ID not found.");
        }

        setVisible(false);
        new UpdateStock().setVisible(true);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Date Field is invalid. Use the format 'dd/MM/yyyy'.");
    }

 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtdoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdoeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdoeActionPerformed

    private void txtsuplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsuplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsuplActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField medid;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtdoe;
    private javax.swing.JTextField txtdom;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtsupl;
    // End of variables declaration//GEN-END:variables
}
